version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: alline_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alline
      POSTGRES_PASSWORD: alline123
      POSTGRES_DB: alline_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alline -d alline_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    

volumes:
  postgres_data:
